; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:giga_r1_m4]
platform = ststm32
board = giga_r1_m7
framework = arduino
lib_extra_dirs = /Users/tristan/Library/Mobile Documents/com~apple~CloudDocs/Development/libs

[platformio]
description = Handles all date & time related tasks by creating powerful global functions that are deeply integrated into a smart pair of object oriented classes
